### ISSUE TITLE
Confusing Key Rule

### ISSUE THREAD

**Issue by magic-happenz** [Azure/KeyVault-Secrets-Rotation-StorageAccount-PowerShell#1]
Hello,
I am currently using this template for my own key rotation and was wondering about this part of the runbook:
`    If ($credentialId -eq 'key1') {
        return "key2"
    }
    Else {
        return "key1"
    }`
https://github.com/Azure/KeyVault-Secrets-Rotation-StorageAccount-PowerShell/blob/main/AKVStorageAccountRotation/run.ps1#L21-L27

I am just beginner so I thought I will ask directly. For me it looks like you are returning key2 when key1 should be returned. In my environment I guess that is why keys are always mixed up. Is there a reason for this or is it just a typo?

Cheers.

**Comment by jlichwa** [comment]
The function is to get alternate key. If current key is key1 (which you get from the event), you return key2. 
You always rotate alternate key to avoid disruption to application which using current key to connect to Storage.
Based on RP this function needs to be updated - it can be PrimaryKey, SecondaryKey or User1, User2 etc...  You always need to have 2 credentials for resource and rotate alternate one, so application using the key is not disrupted during rotation.
